services:
  otel:
    container_name: otel
    hostname: otel
    image: otel/opentelemetry-collector-contrib:0.110.0
    restart: always
    command:
      - --config=/opt/otel/config.yaml
    volumes:
      - ./docker/otel.yaml:/opt/otel/config.yaml
    ports:
      - 1888:1888
      - 8888:8888
      - 8889:8889
      - 13133:13133
      - 4317:4317
      - 4318:4318
      - 55679:55679
    depends_on:
      - zipkin
      - jaeger
      - tempo

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.54.1
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/opt/prometheus/config.yaml
    volumes:
      - ./docker/prometheus.yaml:/opt/prometheus/config.yaml
    ports:
      - 9090:9090

  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki:3.2.0
    ports:
      - 3100:3100

  tempo:
    container_name: tempo
    hostname: tempo
    image: grafana/tempo:2.6.0
    command:
      - --config.file=/opt/tempo/config.yaml
    volumes:
      - ./docker/tempo.yaml:/opt/tempo/config.yaml
    ports:
      - 3200:3200

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:11.2.2
    volumes:
      - ./docker/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - 3000:3000

  jaeger:
    container_name: jaeger
    hostname: jaeger
    image: jaegertracing/all-in-one:1.61.0
    restart: always
    ports:
      - 16686:16686
      - 14268
      - 14250

  zipkin:
    container_name: zipkin
    hostname: zipkin
    image: openzipkin/zipkin:3.4.1
    restart: always
    ports:
      - 9411:9411
