management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

spring:
  application:
    name: actuator-spring-sample

