receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      label1: otel
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin,otlp/jaeger,otlp/tempo,logging]